# NumOy Essential Training: 1 Foundations of NumPy

## 1. NumPy Overview and Introduction to Jypyter Notebook

### Why should I use NumPy?

- Python was not initially disigned for numerical computing
- Need faster vector operations
- Numpy - computations completed efficiently
- Most important package for scientific computing 
- Numpy:
    - Arithmetic operations
    - Statistics operations
    - Bitwise operations
    - Copying and viewing arrays
    - Stacking
    - Searching, sorting, counting
    - Mathematical operations
    - Linear algebra
    - Broadcasting
    - Matrix operations

#### PYTHON LISTS

- No support for vectorized operations
- No fixed typed elements
- For loops not efficient

#### NUMPY ARRAYS

- Supports vectorized operations (addicion, multiplications)
- Fixed data type
- More efficient

#### Cleaner than Python code

- Same tasks, fewer lines
- Fewer loops

#### Aplication

- Machine lerarning 
- Used in libraries

### Python lists vs. Numpy arrays

- Goal: store data
- Both are ordered, mutable, duplicate
- Both have indexing, iteratins, slicing

In [1]:
# python list
list = [1, 1, 2, 3, 3]

In [2]:
# numpy array

import numpy as np

np.array([1, 1, 2, 3, 3])

array([1, 1, 2, 3, 3])

- lists are built-in data structures, while arrays must be imported
- lists expands as we add new elements
- for Numpy arrays, once we define the dimension, it cannot be changed
- Numpy arrays consume less memory
- example: 1000 elements - numpy arrays consumes six times less memory
- lists stores more infomation: object value, object type, reference count, size
- Numpy arrays are faster
- example: multiply the values in array by 5, numpy is faster because ```array * 5```, no need for the ```for``` loop
- array are convenient to use

In [9]:
import time
import random

In [4]:
start_time = time.time()
# cria uma list python com 10000 elementos
lista = [random.randint(1, 100) for _ in range(10000)]

# multiplica tudo por 5
for i in range(10000):
    lista[i] *= 5
    
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0 seconds ---


In [5]:
start_time = time.time()

arr = np.random.randint(1, 100, size=10000)
arr * 5

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0 seconds ---


In [6]:
# Verificando o tamanho da memória em bytes
import sys
tamanho_memoria = sys.getsizeof(lista)
print(f"Tamanho da memória ocupado pela lista: {tamanho_memoria} bytes")
tamanho_memoria = sys.getsizeof(arr)
print(f"Tamanho da memória ocupado pelo array: {tamanho_memoria} bytes")

Tamanho da memória ocupado pela lista: 85176 bytes
Tamanho da memória ocupado pelo array: 40112 bytes


### Jupyter Notebok basics

### Chapter Quiz

## 2. NumPy Array Types and Creating NumPy Arrays

- **ndarrays**: multidimensional arrays

In [7]:
integers = np.array([10, 20, 30 , 40, 50])

In [8]:
print(integers) 

[10 20 30 40 50]


In [9]:
integers[0]

10

In [10]:
integers[0] = 20
integers

array([20, 20, 30, 40, 50])

In [11]:
# trying with float number
integers[0] = 21.0917320971
integers
# all data have to be of same type

array([21, 20, 30, 40, 50])

In [12]:
integers.dtype

dtype('int32')

In [13]:
smallIntegers = np.array(integers, dtype=np.int8)
smallIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [14]:
largeIntegers = np.array(integers, dtype=np.int64)
largeIntegers

array([21, 20, 30, 40, 50], dtype=int64)

In [15]:
print(integers.nbytes)
print(smallIntegers.nbytes)
print(largeIntegers.nbytes)

20
5
40


In [16]:
floats = np.array([1.2, 2.3, 3.4, 4.5])
print(floats)

[1.2 2.3 3.4 4.5]


In [17]:
floats.dtype

dtype('float64')


### Array types and conversions betwewn types

- **vector**: 1 dimension
- **matrix**: 2 dimensions
- **tensor**: 3 dimensions


In [18]:
nums = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
nums[0][0]

1

In [20]:
nums[1][4]

10

In [21]:
nums.ndim

2


### Multidimentional arrays

In [22]:
multi_arr=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
multi_arr[0][0][0]

1

In [24]:
multi_arr[0, 0, 0]

1

In [25]:
multi_arr[1, 0, 2]

9

In [26]:
multi_arr.ndim

3



### Creating arrays from lists and other Python structures


In [27]:
first_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [28]:
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [29]:
first_array = np.array(first_list)

In [30]:
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# creating a mixe dlist to see result in array
second_list = [1, 2, 3, -1.23, 12800000.56]
second_array=np.array(second_list)

In [32]:
second_array

array([ 1.00000000e+00,  2.00000000e+00,  3.00000000e+00, -1.23000000e+00,
        1.28000006e+07])

In [33]:
second_array.dtype

dtype('float64')

In [34]:
# mixing strings and numbers
third_list = ['Ann', 11111, 'Peter', 2222]
third_array = np.array(third_list)

In [35]:
# all the elements are now strings
third_array

array(['Ann', '11111', 'Peter', '2222'], dtype='<U11')

In [36]:
# creating arrays from tuples (imutable, cannot be changed)
first_tuple = (5, 10, 15, 20, 25, 30)


In [37]:
array_from_tuple = np.array(first_tuple)

In [38]:
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [39]:
array_from_tuple.dtype

dtype('int32')

In [40]:
# now create a multidimensional array
multi_dim_list = [[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]]
arr_from_multi_dim_list = np.array(multi_dim_list)

In [41]:
arr_from_multi_dim_list

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Intrinsic NumPy arrays creation

In [42]:
# initializing an array with arange
integers_array = np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
integers_second_array = np.arange(100, 130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [44]:
integers_third_array = np.arange(100, 151, 2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [45]:
# initializing an arry with float
first_floats = np.linspace(10, 20)
first_floats

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [46]:
second_floats = np.linspace(10, 20, 5)
second_floats

array([10. , 12.5, 15. , 17.5, 20. ])

In [47]:
# initializing with random numbers
first_rand_arr = np.random.rand(10)
first_rand_arr

array([0.46698671, 0.24300135, 0.44183457, 0.91537462, 0.80050098,
       0.73736733, 0.77574427, 0.24457086, 0.66758524, 0.89927581])

In [48]:
second_rand_arr = np.random.rand(4, 4)
second_rand_arr

array([[0.20040721, 0.66637037, 0.1574066 , 0.15750915],
       [0.94092081, 0.99460093, 0.50878477, 0.96269732],
       [0.27529836, 0.07917834, 0.82785929, 0.67124609],
       [0.3839903 , 0.20060214, 0.73438596, 0.1847541 ]])

In [49]:
third_rand_arr = np.random.randint(0, 100, 20)
third_rand_arr

array([ 6, 76, 88, 24, 79, 17, 25,  1, 90, 20,  8, 28, 38, 75, 71, 31, 92,
        1, 96, 22])

### Creating arrays filled with constant values

In [50]:
# creating arrays with all zeros
first_z_array = np.zeros(5)
first_z_array

array([0., 0., 0., 0., 0.])

In [51]:
second_z_array = np.zeros((4, 5))
second_z_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
# creating arrays with all ones
first_ones_array = np.ones(6)
first_ones_array

array([1., 1., 1., 1., 1., 1.])

In [53]:
second_ones_array = np.ones((7, 8))
second_ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [54]:
third_ones_array = np.ones((4, 5), dtype=int)
third_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [55]:
# creating an empty array and filling it
first_fill_array = np.empty(10, dtype=int)
first_fill_array.fill(12)
first_fill_array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [56]:
# creating arrays using full
first_full_array = np.full(5, 10)
first_full_array

array([10, 10, 10, 10, 10])

In [57]:
second_full_array = np.full((4, 5), 8)
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

### Finding the shape and size of an array

- dtype
- ndim
- size
- shape

In [58]:
first_arr = np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [59]:
second_arr = np.linspace((1, 2), (10, 20), 10)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [60]:
third_arr = np.full((2, 2, 2), 10)
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [61]:
# finding the shape of the array
np.shape(first_arr)

(20,)

In [62]:
np.shape(second_arr)

(10, 2)

In [63]:
np.shape(third_arr)

(2, 2, 2)

In [64]:
# fixing the size of the array
np.size(first_arr)

20

In [65]:
np.size(second_arr)

20

In [66]:
np.size(third_arr)

8

### Chapter Quiz

## 3. Manipulate NumPy Arrays

### Adding, removing, and sorting elements

In [3]:
first_arr = np.array([1, 2, 3, 5])
first_arr

array([1, 2, 3, 5])

In [4]:
# numpy.insert(arr, obj, values, axis=None)
new_first_arr = np.insert(first_arr, 3, 4)
new_first_arr

array([1, 2, 3, 4, 5])

In [5]:
second_arr = np.array([1, 2, 3, 4])
second_arr

array([1, 2, 3, 4])

In [6]:
# numpy.append(arr, values, axis=None)
new_second_arr = np.append(second_arr, 5)
new_second_arr

array([1, 2, 3, 4, 5])

In [7]:
third_arr = np.array([1, 2, 3, 4, 5])
third_arr

array([1, 2, 3, 4, 5])

In [8]:
# numpy.delete(arr, obj, axis=None)
del_arr = np.delete(third_arr, 4)
del_arr

array([1, 2, 3, 4])

In [10]:
# random.randint(low, high=None, size=None, dtype=int)
integers_arr = np.random.randint(0, 20, 20)
integers_arr

array([12, 15,  0,  7, 19, 14, 15,  1,  0, 11, 14, 11, 10, 10, 15,  5,  9,
       17,  6,  3])

In [11]:
# sort(a[, axis, kind, order, stable])
print(np.sort(integers_arr))

[ 0  0  1  3  5  6  7  9 10 10 11 11 12 14 14 15 15 15 17 19]


In [22]:
integers_arr = np.random.randint(0, 20, 20)
integers_arr

array([14,  7, 11, 11, 11, 13,  0, 14, 10,  9,  4,  5,  7, 18,  4,  7, 19,
        4, 10, 17])

In [23]:
integers_2dim_arr = np.array([[3, 2, 5, 7, 4], [5, 0, 8, 3, 1]])
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [24]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [25]:
colors = np.array(['orange', 'red', 'green', 'blue'])
colors

array(['orange', 'red', 'green', 'blue'], dtype='<U6')

In [26]:
print(np.sort(colors))

['blue' 'green' 'orange' 'red']


### Copies and views

Some functions returns copy and some return view.

#### Copy

- New array.
- Physically stored at another location.

#### View

- Different view of the original array.
- Gives a differently named reference to the same location in the memory.

In [27]:
students_ids_number = np.array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [28]:
students_ids_number_reg = students_ids_number
print("id of students_ids_number", id(students_ids_number))
print("id of students_ids_number_reg", id(students_ids_number_reg))

id of students_ids_number 2393449776304
id of students_ids_number_reg 2393449776304


In [29]:
students_ids_number_reg[1] = 2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


Both arrays changed. We can conclude that assignments don't make a copy of an arrays object. Any changes we make, get reflected in the other array.

In [30]:
# creating a copy of the array
students_ids_number_cp = students_ids_number.copy()
students_ids_number_cp

array([1111, 2222, 1313, 1414, 1515, 1616, 1717, 1818])

In [31]:
print(students_ids_number_cp == students_ids_number)

[ True  True  True  True  True  True  True  True]


In [34]:
# different locations in memory
print("original: ", id(students_ids_number))
print("copy: ", id(students_ids_number_cp))

original:  2393449776304
copy:  2393450043824


In [33]:
students_ids_number[0] = 1000
print(students_ids_number)
print(students_ids_number_cp)

[1000 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [35]:
# creating a view
students_ids_number_v = students_ids_number.view()

In [37]:
# changes on the original affects the view and vice versa
students_ids_number_v[0] = 2000
print("original: ", students_ids_number)
print("view: ", students_ids_number_v)

original:  [2000 2222 1313 1414 1515 1616 1717 1818]
view:  [2000 2222 1313 1414 1515 1616 1717 1818]


In [38]:
print(students_ids_number.base)
print(students_ids_number_cp.base)
print(students_ids_number_v.base)
# None is returned in case the array owns the data

None
None
[2000 2222 1313 1414 1515 1616 1717 1818]


### Reshaping arrays

Change the arrangement of the array so, the shape of the array changes while the number of elements stays the same.

In [39]:
first_arr = np.arange(1, 13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
second_arr = np.reshape(first_arr, (3, 4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
third_arr = np.reshape(first_arr, (6, 2))
third_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [43]:
# error - wrong dimensions
fourth_arr = np.reshape(first_arr, (4, 4))

ValueError: cannot reshape array of size 12 into shape (4,4)

In [44]:
fifth_arr = np.reshape(first_arr, (3, 2, 2))
print(fifth_arr)
print("Dimensions of fifth_arr is ", fifth_arr.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of fifth_arr is  3


In [47]:
sixth_arr = np.array([[1, 2], [3, 4], [5, 6]])
sixth_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
# creating one dimensional array
seventh_arr_flat = np.reshape(sixth_arr, -1)
seventh_arr_flat

array([1, 2, 3, 4, 5, 6])

In [50]:
'''
numpy.ravel
numpy.ravel(a, order='C')[source]
Return a contiguous flattened array.
'''
eigth_arr_flat = sixth_arr.flatten()
print("eighth_arr_flat: ", eigth_arr_flat)
ninth_arr_rav = sixth_arr.ravel()
print("ninth_arr_rav: ", ninth_arr_rav)

eighth_arr_flat:  [1 2 3 4 5 6]
ninth_arr_rav:  [1 2 3 4 5 6]


In [51]:
eigth_arr_flat[0] = 100

In [52]:
ninth_arr_rav[0] = 200

In [54]:
print("eigth_arr_flat: ", eigth_arr_flat)
print("ninth_arr_rav: ", ninth_arr_rav)
print("sixth_arr: ", sixth_arr)

eigth_arr_flat:  [100   2   3   4   5   6]
ninth_arr_rav:  [200   2   3   4   5   6]
sixth_arr:  [[200   2]
 [  3   4]
 [  5   6]]


### Indexing and slicing

Advantage of NumPy: manipulate large amout of data without writting inefficient loops.

#### Index 

- arr[0]

#### Slice

- arr[1:4]

In [55]:
twodim_arr = np.reshape(np.arange(12), (3, 4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
twodim_arr[1, 1]

5

In [57]:
twodim_arr[1]

array([4, 5, 6, 7])

In [58]:
threedim_arr = np.reshape(np.arange(3*4*5), (3, 4, 5))
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [59]:
threedim_arr[0, 2, 3]

13

In [61]:
threedim_arr[-1, -1, -1]

59

In [62]:
onedim_arr = np.arange(10)
onedim_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
onedim_arr[2:6]

array([2, 3, 4, 5])

In [64]:
# first 5 elements
onedim_arr[:5]

array([0, 1, 2, 3, 4])

In [65]:
# last 3 elements
onedim_arr[-3:]

array([7, 8, 9])

In [66]:
# every 2/other elements
onedim_arr[::2]

array([0, 2, 4, 6, 8])

In [67]:
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
twodim_arr[1:, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [70]:
twodim_arr[1, :]

array([4, 5, 6, 7])

In [71]:
twodim_arr[:, 2]

array([ 2,  6, 10])

### Joining and splitting arrays

Functions for joining arrays:

- concatenate
- stack
- hstack
- vsatack

In [74]:
first_arr = np.arange(1, 11)
second_arr = np.arange(11, 21)
print("first_arr: ", first_arr)
print("second_arr: ", second_arr)

first_arr:  [ 1  2  3  4  5  6  7  8  9 10]
second_arr:  [11 12 13 14 15 16 17 18 19 20]


In [78]:
# numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
# Join a sequence of arrays along an existing axis.
con_arr = np.concatenate((first_arr, second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [79]:
third_2darr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
third_2darr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [80]:
fourth_2darr = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
fourth_2darr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [81]:
con2d_arr = np.concatenate((third_2darr, fourth_2darr), axis=1)
con2d_arr

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [82]:
'''
numpy.stack
numpy.stack(arrays, axis=0, out=None, *, dtype=None, casting='same_kind')[source]
Join a sequence of arrays along a new axis.
'''
st_arr = np.stack((first_arr, second_arr))
st_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [83]:
'''
numpy.hstack
numpy.hstack(tup, *, dtype=None, casting='same_kind')[source]
Stack arrays in sequence horizontally (column wise).
'''
hst_arr = np.hstack((first_arr, second_arr))
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [84]:
'''
numpy.vstack
numpy.vstack(tup, *, dtype=None, casting='same_kind')[source]
Stack arrays in sequence vertically (row wise).
'''
vst_arr = np.vstack((first_arr, second_arr))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

Functions for splitting arrays:

- split
- array_split
- hsplit
- vsplit

In [85]:
fifth_arr = np.arange(1, 13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [86]:
'''
numpy.array_split
numpy.array_split(ary, indices_or_sections, axis=0)[source]
Split an array into multiple sub-arrays.
'''
sp_arr = np.array_split(fifth_arr, 4)
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [87]:
print(sp_arr[1])

[4 5 6]


In [88]:
sp_arr = np.array_split(fifth_arr, 8)
sp_arr

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [89]:
hs_arr=np.hsplit(third_2darr, 5)
hs_arr

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [90]:
vs_arr = np.vsplit(third_2darr, 2)
vs_arr

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

### Chapter Quiz

## 4. Functions and Operations

### Arithmetic operations and functions

- Vectorization: operations can be executed in parallel on multiple elements of the array.

Operations:

- addition
- subtraction
- multiplication
- division
- exponentiation
- specific functions to perform 

In [91]:
a = np.arange(1, 11)
b = np.arange(21, 31)
print("a: ", a)
print("b: ", b)

a:  [ 1  2  3  4  5  6  7  8  9 10]
b:  [21 22 23 24 25 26 27 28 29 30]


In [92]:
a + b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [93]:
b - a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [94]:
a * b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [95]:
b / a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [96]:
c = np.arange(2, 12)
print("c: ", c)

c:  [ 2  3  4  5  6  7  8  9 10 11]


In [97]:
a ** c

array([         1,          8,         81,       1024,      15625,
           279936,    5764801,  134217728, -808182895, 1215752192])

In [98]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [99]:
np.add(a, b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [100]:
np.subtract(b, a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [101]:
np.multiply(a, b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [102]:
np.divide(b, a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [103]:
np.mod(b, a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

In [104]:
np.power(a, c)

array([         1,          8,         81,       1024,      15625,
           279936,    5764801,  134217728, -808182895, 1215752192])

In [105]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

### Broadcasting

- The term **broadcasting** describes how NumPy treats arrays with different shapes during arithmetic operations.
- Subject to certain constraints, the smaller array is **broadcast** across the larger array so that they have compatible shapes.
- Dimensions are compatible: if their axes on a a noe-by-one basis, they have either **the same length** or a **length of one**.

In [106]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
b  = np.arange(1, 4)
b

array([1, 2, 3])

In [108]:
a + b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [109]:
c = np.arange(1, 3)
c

array([1, 2])

In [110]:
# broadcasting error 
a + c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [112]:
d = np.arange(24).reshape(2, 3, 4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [114]:
e = np.arange(4)
e

array([0, 1, 2, 3])

In [115]:
d - e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

### Aggregate functions

In [117]:
first_arr = np.arange(10, 110, 10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [118]:
second_arr = np.arange(10, 100, 10).reshape(3, 3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [120]:
third_arr = np.arange(10, 110, 10).reshape(2, 5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [121]:
first_arr.sum()

550

In [122]:
second_arr.sum()

450

In [123]:
# colunms
second_arr.sum(axis=0)

array([120, 150, 180])

In [124]:
# lines
second_arr.sum(axis=1)

array([ 60, 150, 240])

In [125]:
first_arr.prod()

1704722432

In [126]:
second_arr.prod()

-1786839040

In [127]:
third_arr.prod()

1704722432

In [128]:
third_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

In [129]:
np.average(first_arr)

55.0

In [130]:
np.average(second_arr)

50.0

In [131]:
np.average(third_arr)

55.0

In [132]:
# minimum value
np.min(first_arr)

10

In [133]:
# maximum value
np.max(first_arr)

100

In [134]:
np.mean(first_arr)

55.0

In [135]:
np.std(first_arr)

28.722813232690143

### How to get unique items and counts


In [136]:
first_arr = np.array([1, 2, 3, 4, 5, 6, 1, 2, 7, 1, 2, 10, 7, 8])
first_arr

array([ 1,  2,  3,  4,  5,  6,  1,  2,  7,  1,  2, 10,  7,  8])

In [137]:
np.unique(first_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [139]:
second_arr = np.array([[1, 1, 2, 1], [3, 1, 2, 1], [1, 1, 2, 1], [7, 1, 1, 1]])
second_arr

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [140]:
np.unique(second_arr)

array([1, 2, 3, 7])

In [141]:
np.unique(second_arr, axis=0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [142]:
np.unique(second_arr, axis=1)

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

In [143]:
np.unique(first_arr, return_index=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([ 0,  1,  2,  3,  4,  5,  8, 13, 11], dtype=int64))

In [146]:
np.unique(second_arr, return_counts=True)

(array([1, 2, 3, 7]), array([11,  3,  1,  1], dtype=int64))


### Transpose like operations

In [147]:
first_2dimarr = np.arange(12).reshape((3, 4))
first_2dimarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
np.transpose(first_2dimarr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [149]:
second_2dimarr = np.arange(6).reshape(3, 2)
second_2dimarr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [150]:
np.transpose(second_2dimarr)

array([[0, 2, 4],
       [1, 3, 5]])

In [151]:
np.transpose(second_2dimarr, (1, 0))

array([[0, 2, 4],
       [1, 3, 5]])

In [152]:
first_3dimarr = np.arange(24).reshape(2, 3, 4)
first_3dimarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [153]:
np.moveaxis(first_3dimarr, 0, -1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [154]:
np.swapaxes(first_3dimarr, 0, 2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

### Reversing an array

In [155]:
arr_1dim = [10, 1, 9, 2, 8, 3, 7, 4, 6, 5]
arr_1dim

[10, 1, 9, 2, 8, 3, 7, 4, 6, 5]

In [156]:
arr_1dim[::-1]

[5, 6, 4, 7, 3, 8, 2, 9, 1, 10]

In [157]:
np.flip(arr_1dim)

array([ 5,  6,  4,  7,  3,  8,  2,  9,  1, 10])

In [161]:
arr_2dim = np.arange(9).reshape(3, 3)
arr_2dim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [162]:
np.flip(arr_2dim)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [163]:
np.flip(arr_2dim, 1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [164]:
arr_3dim = np.arange(24).reshape(2, 3, 4)
arr_3dim

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [165]:
np.flip(arr_3dim, 1)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [166]:
np.flip(arr_3dim, 2)

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])

### Chapter Quiz

## Conclusion