# 1. Introduction to NumPy

## NumPy Intro

https://www.w3schools.com/python/numpy_intro.asp

### What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy stands for Numerical Python.

### Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ```ndarray```, it provides a lot of supporting functions that make working with ```ndarray``` very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

### Why Numpy is Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

### Which Language is NumPy written in?

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

https://github.com/numpy/numpy

# 2. NumPy Getting Started

## Import Numpy

In [2]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


NumPy is usually imported under the ```np``` alias.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## Checking NumPy Version

In [2]:
import numpy as np

print(np.__version__)

1.17.4


# 3. NumPy Creating Arrays

## Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ```ndarray```.

We can create a NumPy ```ndarray``` object by using the ```array()``` function.

In [6]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# using a tuple to create a numPy array

arr = np.array((1, 2, 3, 4, 5))

print(arr) 

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimensions in Arrays

In [8]:
# Create a 0-D array with value 42

arr = np.array(42)

print(arr) 

42


In [9]:
# Create a 1-D array containing the values 1,2,3,4,5:
    
arr = np.array([1, 2, 3, 4, 5])

print(arr) 

[1 2 3 4 5]


NumPy has a whole sub module dedicated towards matrix operations called ```numpy.mat```.

In [11]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr) 

[[1 2 3]
 [4 5 6]]


In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check Number of Dimensions

In [13]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays

In [14]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## 4. NumPy Array Indexing

### Access Array Elements

Array indexing is the same as accessing an array element.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0]) # first element

1


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1]) # second element

2


### Access 2-D Arrays

In [7]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1]) # Access the 2nd element on 1st dim

2nd element on 1st dim:  2


In [8]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4]) # Access the 5th element on 2nd dim

5th element on 2nd dim:  10


### Access 3-D Arrays

In [9]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2]) 

6


### Negative Indexing

Use negative indexing to access an array from the end.

In [10]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1]) 

Last element from 2nd dim:  10


## 5. NumPy Array Slicing

### Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: ```[start:end]```.

We can also define the step, like this: ```[start:end:step]```.

**Note**: The result includes the start index, but excludes the end index.

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Slice elements from index 1 to index 5
print(arr[1:5])

[2 3 4 5]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Slice elements from index 4 to the end of the array
print(arr[4:]) 

[5 6 7]


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Slice elements from the beginning to index 4 (not included)
print(arr[:4]) 

[1 2 3 4]


### Negative Slicing

Use the minus operator to refer to an index from the end:

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1]) 

[5 6]


### STEP

Use the ```step``` value to determine the step of the slicing:

In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2]) # step = 2

[2 4]


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2]) 

[1 3 5 7]


### Slicing 2-D Arrays



In [19]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) 

[7 8 9]


In [21]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# From both elements, return index 2
print(arr[0:2, 2]) 

[3 8]


In [22]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4]) 

[[2 3 4]
 [7 8 9]]


## 6. NumPy Data Types

### Data Types in Python

By default Python have these data types:

- ```strings``` - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- ```integer``` - used to represent integer numbers. e.g. -1, -2, -3
- ```float``` - used to represent real numbers. e.g. 1.2, 42.42
- ```boolean``` - used to represent True or False.
- ```complex``` - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

### Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.


- ```i``` - integer
- ```b``` - boolean
- ```u``` - unsigned integer
- ```f``` - float
- ```c``` - complex float
- ```m``` - timedelta
- ```M``` - datetime
- ```O``` - object
- ```S``` - string
- ```U``` - unicode string
- ```V``` - fixed chunk of memory for other type ( void )

### Checking the Data Type of an Array

The NumPy array object has a property called ```dtype``` that returns the data type of the array:

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype) # Get the data type of an array object
print(arr)

int64
[1 2 3 4]


In [27]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype) # Get the data type of an array containing strings

<U6


### Creating Arrays With a Defined Data Type

We use the ```array()``` function to create arrays, this function can take an optional argument: ```dtype``` that allows us to define the expected data type of the array elements:

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) 

[b'1' b'2' b'3' b'4']
|S1


For ```i```, ```u```, ```f```, ```S``` and ```U``` we can define size as well.

In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


### Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the ```astype()``` method.

The ```astype()``` function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like ```'f'``` for float, ```'i'``` for integer etc. or you can use the data type directly like float for ```float``` and ```int``` for integer.

In [38]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

# Change data type from float to integer by using 'i' as parameter value:
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


In [39]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

# Change data type from float to integer by using int as parameter value
newarr = arr.astype(int) 

print(newarr)
print(newarr.dtype) 

[1 2 3]
int64


In [40]:
import numpy as np

arr = np.array([1, 0, 3])

# Change data type from integer to boolean:
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype) 

[ True False  True]
bool


## 7. NumPy Array Copy vs View

### The Difference Between Copy and View

The main difference between a **copy** and a **view** of an array is that the **copy is a new array, and the view is just a view of the original array**.

The *copy owns the data* and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The *view does not own the data* and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

### COPY

In [42]:
# Make a copy, change the original array, and display both arrays:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


### VIEW

In [44]:
# Make a view, change the original array, and display both arrays:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x) 

[31  2  3  4  5]
[31  2  3  4  5]


### Check if Array Owns it's Data

Every NumPy array has the attribute ```base``` that returns ```None``` if the array owns the data.

Otherwise, the ```base``` attribute refers to the original object. 

In [46]:
 import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
