# Introduction to NumPy

## NumPy Intro

https://www.w3schools.com/python/numpy_intro.asp

### What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy stands for Numerical Python.

### Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ```ndarray```, it provides a lot of supporting functions that make working with ```ndarray``` very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

### Why Numpy is Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

### Which Language is NumPy written in?

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

https://github.com/numpy/numpy

# NumPy Getting Started

## Import Numpy

In [2]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


NumPy is usually imported under the ```np``` alias.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## Checking NumPy Version

In [4]:
import numpy as np

print(np.__version__)

1.17.4


# NumPy Creating Arrays

## Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ```ndarray```.

We can create a NumPy ```ndarray``` object by using the ```array()``` function.

In [6]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# using a tuple to create a numPy array

arr = np.array((1, 2, 3, 4, 5))

print(arr) 

[1 2 3 4 5]


## Dimensions in Arrays

In [8]:
# Create a 0-D array with value 42

arr = np.array(42)

print(arr) 

42


In [9]:
# Create a 1-D array containing the values 1,2,3,4,5:
    
arr = np.array([1, 2, 3, 4, 5])

print(arr) 

[1 2 3 4 5]


NumPy has a whole sub module dedicated towards matrix operations called ```numpy.mat```.

In [11]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr) 

[[1 2 3]
 [4 5 6]]


In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check Number of Dimensions

In [13]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays

In [14]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5
